### PR TITLE
♻️ Extract `clean_up_values_columns()`

### PR DESCRIPTION
**Pull request by nepito**
- [ ] Formar with Styler `R/tm_expiring_contracts.R` and `tests/testthat/test-transfermarkt.R`
- [ ] Extract function `clean_up_values_columns()`
- [ ] Test function `clean_up_values_columns()`

### CODE REVIEW

**Comment by nepito** [comment]
Hello @JaseZiv.

So far I've extracted a function and standardized the format to the files I'll be working with.

With these changes, I have already modified more than 100 lines. Since making a pull request that extensive is not recommended, please could we try to close this pull request before adding more changes?

We haven't fixed the bug yet, but with these changes, I'm already familiar with the code.

Greetings.

**Comment by nepito** [comment]
@JaseZiv,  the [action](https://github.com/JaseZiv/worldfootballR/actions/runs/3784407146/jobs/6433692615) is failing.

We have a problem with the `load_fb_big5_advanced_season_stats()` function when using the stat type *shooting* for the *player*.

This error does not occur when we want the *shooting* statistics for the *team*. Nor when we ask for the stat type *gca* of the *player*.

The tests use the combination "shooting" and "player" so they fail. I think the problem comes from the data, but the data hasn't changed in two months.

What do you think?

image

**Comment by JaseZiv** [comment]
> @JaseZiv, the [action](https://github.com/JaseZiv/worldfootballR/actions/runs/3784407146/jobs/6433692615) is failing.
> 
> We have a problem with the `load_fb_big5_advanced_season_stats()` function when using the stat type _shooting_ for the _player_.
> 
> This error does not occur when we want the _shooting_ statistics for the _team_. Nor when we ask for the stat type _gca_ of the _player_.
> 
> The tests use the combination "shooting" and "player" so they fail. I think the problem comes from the data, but the data hasn't changed in two months.
> 
> What do you think?
> 
> image

Interesting.

I’m currently on holidays but I will look at this over the next few days.

Appreciate your help. I will be in touch.

**Comment by JaseZiv** [comment]
@nepito, Given this PR hasn't addressed the issue it was meant to be addressing, I am going to close it.

Can you please withhold committing stylistic changes as it's making reviewing material changes difficult. While the current code might not tick all the stylistic boxes, I'd rather leave the style changes to one massive commit that I'll do at some point in the future.

Feel free to resubmit a PR to address any currently open issues.

Thanks.

**Comment by nepito** [comment]
Very good @JaseZiv, so I continue with the plan to solve this issue #212.

Can I add a new file for the necessary tests?

**Comment by JaseZiv** [comment]
Yeah for sure @nepito, feel free to create a new PR with less cosmetic changes.

Thanks

**Comment by nepito** [comment]
Great @JaseZiv. I will do so.

For ease of review: do you prefer a pull request with few lines, even if the issue is not resolved, or do you prefer the issue to be resolved even if there are "many" lines?

**Pull request closed without merging**
